Repository prgrms-web-devcourse/Team_WAS_YAS_BE, pull requests merged in 2021-12, with the labels that each got.

#22 feat : #21/반환응답객체 생성
  .gitignore
  build.gradle
  src/main/java/org/prgrms/yas/domain/comment/domain/Comment.java
  src/main/java/org/prgrms/yas/domain/post/domain/RoutinePost.java
  src/main/java/org/prgrms/yas/domain/routine/domain/Routine.java
  src/main/java/org/prgrms/yas/domain/user/domain/User.java
  src/main/java/org/prgrms/yas/global/ApiResponse.java
  src/main/resources/application-local.yml
Labels: ✨Feature

#23 Chore : gitignore 수정
  .gitignore
  src/main/resources/application-local.yml
Labels: ✨Feature

#20 feat : #12/회원로그인기능
  .gitignore
  build.gradle
  src/main/java/org/prgrms/yas/configures/JwtConfig.java
  src/main/java/org/prgrms/yas/configures/WebSecurityConfig.java
  src/main/java/org/prgrms/yas/domain/comment/domain/Comment.java
  src/main/java/org/prgrms/yas/domain/mission/domain/Mission.java
  src/main/java/org/prgrms/yas/domain/mission/domain/MissionCompletion.java
  src/main/java/org/prgrms/yas/domain/post/domain/RoutinePost.java
  src/main/java/org/prgrms/yas/domain/routine/domain/Routine.java
  src/main/java/org/prgrms/yas/domain/user/controller/UserController.java
  src/main/java/org/prgrms/yas/domain/user/domain/Role.java
  src/main/java/org/prgrms/yas/domain/user/domain/User.java
  src/main/java/org/prgrms/yas/domain/user/dto/UserResponse.java
  src/main/java/org/prgrms/yas/domain/user/dto/UserSignInRequest.java
  src/main/java/org/prgrms/yas/domain/user/dto/UserToken.java
  src/main/java/org/prgrms/yas/domain/user/repository/UserRepository.java
  src/main/java/org/prgrms/yas/domain/user/service/OAuth2UserService.java
  src/main/java/org/prgrms/yas/domain/user/service/UserService.java
  src/main/java/org/prgrms/yas/jwt/Jwt.java
  src/main/java/org/prgrms/yas/jwt/JwtAuthentication.java
  src/main/java/org/prgrms/yas/jwt/JwtAuthenticationFilter.java
  src/main/java/org/prgrms/yas/jwt/JwtAuthenticationProvider.java
  src/main/java/org/prgrms/yas/jwt/JwtAuthenticationToken.java
  src/main/java/org/prgrms/yas/oauth2/OAuth2AuthenticationSuccessHandler.java
Labels: ✨Feature

#15 #5/루틴 생성,수정,삭제 기능 추가
  .gitignore
  build.gradle
  src/main/java/org/prgrms/yas/domain/routine/controller/RoutineController.java
  src/main/java/org/prgrms/yas/domain/routine/domain/Routine.java
  src/main/java/org/prgrms/yas/domain/routine/domain/RoutineCategory.java
  src/main/java/org/prgrms/yas/domain/routine/domain/RoutineCompletion.java
  src/main/java/org/prgrms/yas/domain/routine/domain/Week.java
  src/main/java/org/prgrms/yas/domain/routine/dto/RoutineCreateRequest.java
  src/main/java/org/prgrms/yas/domain/routine/dto/RoutineCreateResponse.java
  src/main/java/org/prgrms/yas/domain/routine/dto/RoutineDeleteResponse.java
  src/main/java/org/prgrms/yas/domain/routine/dto/RoutineUpdateRequest.java
  src/main/java/org/prgrms/yas/domain/routine/dto/RoutineUpdateResponse.java
  src/main/java/org/prgrms/yas/domain/routine/repository/RoutineRepository.java
  src/main/java/org/prgrms/yas/domain/routine/service/RoutineService.java
  src/main/java/org/prgrms/yas/domain/user/domain/User.java
  src/test/java/org/prgrms/yas/domain/routine/controller/RoutineControllerTest.java
  src/test/java/org/prgrms/yas/domain/routine/service/RoutineServiceTest.java
Labels: ✨Feature

#17 #16/루틴 전체조회 기능 추가
  build.gradle
  src/main/java/org/prgrms/yas/domain/routine/controller/RoutineController.java
  src/main/java/org/prgrms/yas/domain/routine/domain/Routine.java
  src/main/java/org/prgrms/yas/domain/routine/dto/RoutineDetailResponse.java
  src/main/java/org/prgrms/yas/domain/routine/repository/RoutineRepository.java
  src/main/java/org/prgrms/yas/domain/routine/service/RoutineService.java
  src/test/java/org/prgrms/yas/domain/routine/controller/RoutineControllerTest.java
  src/test/java/org/prgrms/yas/domain/routine/service/RoutineServiceTest.java
Labels: ✨Feature

#28 refactor : #27/엔티티 수정
  src/main/java/org/prgrms/yas/configures/WebSecurityConfig.java
  src/main/java/org/prgrms/yas/domain/comment/domain/Comment.java
  src/main/java/org/prgrms/yas/domain/mission/domain/Mission.java
  src/main/java/org/prgrms/yas/domain/mission/domain/MissionStatus.java
  src/main/java/org/prgrms/yas/domain/post/domain/RoutinePost.java
  src/main/java/org/prgrms/yas/domain/routine/domain/Routine.java
  src/main/java/org/prgrms/yas/domain/routine/domain/RoutineStatus.java
  src/main/java/org/prgrms/yas/domain/routine/dto/RoutineCreateRequest.java
  src/main/java/org/prgrms/yas/domain/routine/dto/RoutineCreateResponse.java
  src/main/java/org/prgrms/yas/domain/routine/dto/RoutineDetailResponse.java
  src/main/java/org/prgrms/yas/domain/routine/dto/RoutineUpdateRequest.java
  src/main/java/org/prgrms/yas/domain/routine/dto/RoutineUpdateResponse.java
  src/main/java/org/prgrms/yas/domain/routine/service/RoutineService.java
  src/main/java/org/prgrms/yas/domain/user/domain/User.java
  src/test/java/org/prgrms/yas/domain/routine/controller/RoutineControllerTest.java
  src/test/java/org/prgrms/yas/domain/routine/service/RoutineServiceTest.java
Labels: ⚙️Setting

#37 feat : #30/미션생성기능 추가
  src/main/java/org/prgrms/yas/domain/mission/controller/MissionController.java
  src/main/java/org/prgrms/yas/domain/mission/domain/Mission.java
  src/main/java/org/prgrms/yas/domain/mission/domain/MissionStatus.java
  src/main/java/org/prgrms/yas/domain/mission/dto/MissionCreateRequest.java
  src/main/java/org/prgrms/yas/domain/mission/exception/NotFoundMissionException.java
  src/main/java/org/prgrms/yas/domain/mission/repository/MissionRepository.java
  src/main/java/org/prgrms/yas/domain/mission/service/MissionService.java
  src/main/java/org/prgrms/yas/domain/routine/exception/NotFoundRoutineException.java
Labels: ✨Feature

#33 style : 코드 스타일 수정
  src/main/java/org/prgrms/yas/YasApplication.java
  src/main/java/org/prgrms/yas/configures/JwtConfig.java
  src/main/java/org/prgrms/yas/configures/WebSecurityConfig.java
  src/main/java/org/prgrms/yas/domain/BaseEntity.java
  src/main/java/org/prgrms/yas/domain/comment/domain/Comment.java
  src/main/java/org/prgrms/yas/domain/mission/domain/Mission.java
  src/main/java/org/prgrms/yas/domain/mission/domain/MissionStatus.java
  src/main/java/org/prgrms/yas/domain/post/domain/RoutinePost.java
  src/main/java/org/prgrms/yas/domain/routine/controller/RoutineController.java
  src/main/java/org/prgrms/yas/domain/routine/domain/Routine.java
  src/main/java/org/prgrms/yas/domain/routine/domain/RoutineCategory.java
  src/main/java/org/prgrms/yas/domain/routine/domain/RoutineStatus.java
  src/main/java/org/prgrms/yas/domain/routine/domain/Week.java
  src/main/java/org/prgrms/yas/domain/routine/dto/RoutineCreateRequest.java
  src/main/java/org/prgrms/yas/domain/routine/dto/RoutineCreateResponse.java
  src/main/java/org/prgrms/yas/domain/routine/dto/RoutineDeleteResponse.java
  src/main/java/org/prgrms/yas/domain/routine/dto/RoutineDetailResponse.java
  src/main/java/org/prgrms/yas/domain/routine/dto/RoutineUpdateRequest.java
  src/main/java/org/prgrms/yas/domain/routine/dto/RoutineUpdateResponse.java
  src/main/java/org/prgrms/yas/domain/routine/repository/RoutineRepository.java
  src/main/java/org/prgrms/yas/domain/routine/service/RoutineService.java
  src/main/java/org/prgrms/yas/domain/user/controller/UserController.java
  src/main/java/org/prgrms/yas/domain/user/domain/Role.java
  src/main/java/org/prgrms/yas/domain/user/domain/User.java
  src/main/java/org/prgrms/yas/domain/user/dto/UserResponse.java
  src/main/java/org/prgrms/yas/domain/user/dto/UserSignInRequest.java
  src/main/java/org/prgrms/yas/domain/user/dto/UserToken.java
  src/main/java/org/prgrms/yas/domain/user/repository/UserRepository.java
  src/main/java/org/prgrms/yas/domain/user/service/OAuth2UserService.java
  src/main/java/org/prgrms/yas/domain/user/service/UserService.java
  src/main/java/org/prgrms/yas/global/error/ErrorCode.java
  src/main/java/org/prgrms/yas/global/error/GlobalExceptionHandler.java
  src/main/java/org/prgrms/yas/global/error/exception/BusinessException.java
  src/main/java/org/prgrms/yas/global/response/ApiResponse.java
  src/main/java/org/prgrms/yas/global/response/ErrorResponse.java
  src/main/java/org/prgrms/yas/jwt/Jwt.java
  src/main/java/org/prgrms/yas/jwt/JwtAuthentication.java
  src/main/java/org/prgrms/yas/jwt/JwtAuthenticationFilter.java
  src/main/java/org/prgrms/yas/jwt/JwtAuthenticationProvider.java
  src/main/java/org/prgrms/yas/jwt/JwtAuthenticationToken.java
  src/main/java/org/prgrms/yas/oauth2/OAuth2AuthenticationSuccessHandler.java
Labels: 👔Style

#35 feat : Swagger/OpenAPI 설정 추가
  .gitignore
  build.gradle
  src/main/java/org/prgrms/yas/configures/OpenApiConfig.java
  src/main/java/org/prgrms/yas/domain/user/controller/UserController.java
  src/main/java/org/prgrms/yas/domain/user/domain/User.java
Labels: ✨Feature, ⚙️Setting

#39 feat : #36/회원가입기능
  build.gradle
  src/main/java/org/prgrms/yas/domain/user/controller/UserController.java
  src/main/java/org/prgrms/yas/domain/user/domain/User.java
  src/main/java/org/prgrms/yas/domain/user/dto/UserSignUpRequest.java
  src/main/java/org/prgrms/yas/domain/user/exception/CheckPasswordException.java
  src/main/java/org/prgrms/yas/domain/user/exception/DuplicateUserException.java
  src/main/java/org/prgrms/yas/domain/user/exception/NotFoundUserException.java
  src/main/java/org/prgrms/yas/domain/user/repository/UserRepository.java
  src/main/java/org/prgrms/yas/domain/user/service/UserService.java
  src/main/java/org/prgrms/yas/global/error/ErrorCode.java
  src/main/java/org/prgrms/yas/global/error/GlobalExceptionHandler.java
  src/main/java/org/prgrms/yas/global/exception/BusinessException.java
  src/main/java/org/prgrms/yas/global/exception/NotFoundException.java
  src/main/java/org/prgrms/yas/global/response/ErrorResponse.java
Labels: ✨Feature

#40 feat : #38/Mission 삭제 기능 추가
  src/main/java/org/prgrms/yas/domain/mission/controller/MissionController.java
  src/main/java/org/prgrms/yas/domain/mission/domain/Mission.java
  src/main/java/org/prgrms/yas/domain/mission/service/MissionService.java
Labels: ✨Feature

#48 feat : 회원가입 기능
  build.gradle
  src/main/java/org/prgrms/yas/configures/WebSecurityConfig.java
  src/main/java/org/prgrms/yas/domain/user/controller/UserController.java
  src/main/java/org/prgrms/yas/domain/user/domain/User.java
  src/main/java/org/prgrms/yas/domain/user/dto/UserUpdateRequest.java
  src/main/java/org/prgrms/yas/domain/user/exception/IllegalFileException.java
  src/main/java/org/prgrms/yas/domain/user/service/UserService.java
  src/main/java/org/prgrms/yas/global/aws/S3Uploader.java
Labels: ✨Feature

#50 feat : 회원조회 기능
  src/main/java/org/prgrms/yas/domain/user/controller/UserController.java
  src/main/java/org/prgrms/yas/domain/user/domain/User.java
  src/main/java/org/prgrms/yas/domain/user/dto/UserResponse.java
  src/main/java/org/prgrms/yas/domain/user/service/UserService.java
Labels: ✨Feature

#42 feat : #41/미션 전체 조회 기능 추가
  src/main/java/org/prgrms/yas/domain/mission/domain/Mission.java
  src/main/java/org/prgrms/yas/domain/mission/dto/MissionDetailResponse.java
  src/main/java/org/prgrms/yas/domain/routine/controller/RoutineController.java
  src/main/java/org/prgrms/yas/domain/routine/domain/Routine.java
  src/main/java/org/prgrms/yas/domain/routine/dto/RoutineDetailResponse.java
  src/main/java/org/prgrms/yas/domain/routine/dto/RoutineListResponse.java
  src/main/java/org/prgrms/yas/domain/routine/service/RoutineService.java
  src/test/java/org/prgrms/yas/domain/routine/service/RoutineServiceTest.java
Labels: ✨Feature

#51 feat : appsepc.yml 작성
  appspec.yml
Labels: ⚙️Setting

#52 Chore : appsepc.yml 작성
  appspec.yml
Labels: ⚙️Setting

#46 feat : #44/미션 수정 기능 추가
  src/main/java/org/prgrms/yas/domain/mission/controller/MissionController.java
  src/main/java/org/prgrms/yas/domain/mission/domain/Mission.java
  src/main/java/org/prgrms/yas/domain/mission/dto/MissionDetailResponse.java
  src/main/java/org/prgrms/yas/domain/mission/dto/MissionOrder.java
  src/main/java/org/prgrms/yas/domain/mission/dto/MissionUpdateRequest.java
  src/main/java/org/prgrms/yas/domain/mission/repository/MissionRepository.java
  src/main/java/org/prgrms/yas/domain/mission/service/MissionService.java
Labels: ✨Feature

#54 chore : 중괄호 삭제
  appspec.yml
  src/main/java/org/prgrms/yas/domain/user/controller/UserController.java
  src/main/java/org/prgrms/yas/domain/user/service/UserService.java
Labels: 🐞BugFix

#57 refactor: #53/반환객체, 테스트코드 삭제, 예외 수정
  src/main/java/org/prgrms/yas/domain/mission/controller/MissionController.java
  src/main/java/org/prgrms/yas/domain/routine/controller/RoutineController.java
  src/main/java/org/prgrms/yas/domain/routine/dto/RoutineCreateResponse.java
  src/main/java/org/prgrms/yas/domain/routine/dto/RoutineDeleteResponse.java
  src/main/java/org/prgrms/yas/domain/routine/service/RoutineService.java
  src/test/java/org/prgrms/yas/domain/routine/controller/RoutineControllerTest.java
  src/test/java/org/prgrms/yas/domain/routine/service/RoutineServiceTest.java
Labels: 🔧Refactor

#66 refactor : 설정 파일 수정
  build.gradle
  scripts/deploy.sh
  src/main/java/org/prgrms/yas/configures/OpenApiConfig.java
  src/main/java/org/prgrms/yas/global/aws/S3Uploader.java
  src/main/resources/application-local.yml
Labels: 🔧Refactor

#68 Chore : 빌드 파일 수정
  build.gradle
Labels: ⚙️Setting

#69 fix : 배포관련 버그 수정
  src/main/java/org/prgrms/yas/domain/comment/domain/Comment.java
  src/main/java/org/prgrms/yas/domain/mission/domain/MissionStatus.java
  src/main/java/org/prgrms/yas/domain/post/domain/RoutinePost.java
  src/main/java/org/prgrms/yas/domain/routine/domain/Routine.java
  src/main/java/org/prgrms/yas/domain/routine/domain/RoutineStatus.java
  src/main/java/org/prgrms/yas/domain/user/controller/UserController.java
  src/main/resources/application-local.yml
Labels: 🐞BugFix, 🚀Deploy, ⚙️Setting

#70 Fix : 버그 수정
  src/main/java/org/prgrms/yas/domain/comment/domain/Comment.java
  src/main/java/org/prgrms/yas/domain/mission/domain/MissionStatus.java
  src/main/java/org/prgrms/yas/domain/post/domain/RoutinePost.java
  src/main/java/org/prgrms/yas/domain/routine/domain/Routine.java
  src/main/java/org/prgrms/yas/domain/routine/domain/RoutineStatus.java
  src/main/java/org/prgrms/yas/domain/user/controller/UserController.java
Labels: 🐞BugFix, 🚀Deploy, ⚙️Setting

#75 feat : #74/Cors 설정 추가
  src/main/java/org/prgrms/yas/configures/WebConfig.java
Labels: ⚙️Setting

#76 feat : #74/CORS 설정 추가
  src/main/java/org/prgrms/yas/configures/WebConfig.java
Labels: ⚙️Setting

#73 feat : #10/회원삭제기능 구현
  src/main/java/org/prgrms/yas/domain/user/controller/UserController.java
  src/main/java/org/prgrms/yas/domain/user/domain/User.java
  src/main/java/org/prgrms/yas/domain/user/service/UserService.java
Labels: ✨Feature

#87 Feat : 게시글/댓글 API
  src/main/java/org/prgrms/yas/YasApplication.java
  src/main/java/org/prgrms/yas/domain/BaseEntity.java
  src/main/java/org/prgrms/yas/domain/comment/controller/CommentController.java
  src/main/java/org/prgrms/yas/domain/comment/domain/Comment.java
  src/main/java/org/prgrms/yas/domain/comment/dto/CommentCreateRequest.java
  src/main/java/org/prgrms/yas/domain/comment/dto/CommentUpdateRequest.java
  src/main/java/org/prgrms/yas/domain/comment/exception/NotFoundCommentException.java
  src/main/java/org/prgrms/yas/domain/comment/repository/CommentRepository.java
  src/main/java/org/prgrms/yas/domain/comment/service/CommentService.java
  src/main/java/org/prgrms/yas/domain/post/controller/PostController.java
  src/main/java/org/prgrms/yas/domain/post/domain/RoutinePost.java
  src/main/java/org/prgrms/yas/domain/post/dto/CategoryDto.java
  src/main/java/org/prgrms/yas/domain/post/dto/CommentDto.java
  src/main/java/org/prgrms/yas/domain/post/dto/MissionDto.java
  src/main/java/org/prgrms/yas/domain/post/dto/PostDetailResponse.java
  src/main/java/org/prgrms/yas/domain/post/dto/RoutineDto.java
  src/main/java/org/prgrms/yas/domain/post/dto/UserDto.java
  src/main/java/org/prgrms/yas/domain/post/exception/NotFoundRoutinePostException.java
  src/main/java/org/prgrms/yas/domain/post/repository/PostRepository.java
  src/main/java/org/prgrms/yas/domain/post/service/PostService.java
Labels: ✨Feature

#88 refactor : #86/회원조회 응답객체 수정
  src/main/java/org/prgrms/yas/domain/user/domain/User.java
  src/main/java/org/prgrms/yas/domain/user/dto/UserResponse.java
Labels: 🔧Refactor

#93 Refactor : 시간 정규식 수정
  src/main/java/org/prgrms/yas/domain/mission/dto/MissionCreateRequest.java
  src/main/java/org/prgrms/yas/domain/mission/dto/MissionDetailResponse.java
  src/main/java/org/prgrms/yas/domain/mission/dto/MissionStatusUpdateRequest.java
  src/main/java/org/prgrms/yas/domain/routine/dto/RoutineCreateRequest.java
Labels: 🐞BugFix

#100 feat : #92/루틴 전체,완료,미완료 조회 기능 추가
  src/main/java/org/prgrms/yas/domain/routine/controller/RoutineController.java
  src/main/java/org/prgrms/yas/domain/routine/domain/Routine.java
  src/main/java/org/prgrms/yas/domain/routine/domain/Week.java
  src/main/java/org/prgrms/yas/domain/routine/repository/RoutineStatusRepository.java
  src/main/java/org/prgrms/yas/domain/routine/service/RoutineService.java
  src/main/java/org/prgrms/yas/domain/routine/service/Status.java
  src/main/resources/application-local.yml
Labels: ✨Feature

#105 feat : 새로운 기능 추가
  .gitignore
  src/main/java/org/prgrms/yas/domain/mission/domain/Mission.java
  src/main/java/org/prgrms/yas/domain/mission/dto/MissionCreateRequest.java
  src/main/java/org/prgrms/yas/domain/mission/dto/MissionOrder.java
  src/main/java/org/prgrms/yas/domain/mission/service/MissionService.java
  src/main/java/org/prgrms/yas/domain/post/controller/PostController.java
  src/main/java/org/prgrms/yas/domain/post/service/PostService.java
  src/main/java/org/prgrms/yas/domain/routine/controller/RoutineController.java
  src/main/java/org/prgrms/yas/domain/routine/domain/Routine.java
  src/main/java/org/prgrms/yas/domain/routine/domain/Week.java
  src/main/java/org/prgrms/yas/domain/routine/repository/RoutineRepository.java
  src/main/java/org/prgrms/yas/domain/routine/repository/RoutineStatusRepository.java
  src/main/java/org/prgrms/yas/domain/routine/service/RoutineService.java
  src/main/java/org/prgrms/yas/domain/routine/service/Status.java
  src/main/java/org/prgrms/yas/domain/user/controller/UserController.java
  src/main/resources/application-local.yml
Labels: ✨Feature

#107 feat : #106/루틴 상세조회 반환객체에 weeks 추가
  src/main/java/org/prgrms/yas/domain/routine/domain/Routine.java
  src/main/java/org/prgrms/yas/domain/routine/dto/RoutineDetailResponse.java
Labels: 🔧Refactor

#109 feat : #108/루틴,미션 스웨거 설정 추가
  src/main/java/org/prgrms/yas/domain/mission/controller/MissionController.java
  src/main/java/org/prgrms/yas/domain/mission/controller/MissionStatusController.java
  src/main/java/org/prgrms/yas/domain/routine/controller/RoutineController.java
Labels: ⚙️Setting, 🔧Refactor

#113 Refactor : resposne 수정
  src/main/java/org/prgrms/yas/domain/mission/controller/MissionController.java
  src/main/java/org/prgrms/yas/domain/mission/controller/MissionStatusController.java
  src/main/java/org/prgrms/yas/domain/routine/controller/RoutineController.java
  src/main/java/org/prgrms/yas/domain/routine/domain/Routine.java
  src/main/java/org/prgrms/yas/domain/routine/dto/RoutineDetailResponse.java
Labels: 🔧Refactor

#114 Refactor : 스웨거 추가
  src/main/java/org/prgrms/yas/domain/user/controller/UserController.java
Labels: 🔧Refactor

#116 fix : CI/CD 수정
  build.gradle
  src/main/java/org/prgrms/yas/global/aws/S3Uploader.java
Labels: 🐞BugFix, 🔧Refactor

#111 feat: #104/게시물 좋아요 기능 구현
  src/main/java/org/prgrms/yas/domain/likes/controller/LikesController.java
  src/main/java/org/prgrms/yas/domain/likes/domain/PostLikes.java
  src/main/java/org/prgrms/yas/domain/likes/repsitory/PostLikesRepository.java
  src/main/java/org/prgrms/yas/domain/likes/service/LikesService.java
  src/main/java/org/prgrms/yas/domain/post/repository/PostRepository.java
  src/main/java/org/prgrms/yas/domain/user/repository/UserRepository.java
Labels: ✨Feature

#115 feat : #112/댓글좋아요 기능 구현
  src/main/java/org/prgrms/yas/domain/likes/controller/LikesController.java
  src/main/java/org/prgrms/yas/domain/likes/domain/CommentLikes.java
  src/main/java/org/prgrms/yas/domain/likes/repository/CommentLikesRepository.java
  src/main/java/org/prgrms/yas/domain/likes/service/LikesService.java
  src/main/java/org/prgrms/yas/domain/user/repository/UserRepository.java
Labels: ✨Feature

#119 refactor : #95/인가 및 인증 설정 변경
  src/main/java/org/prgrms/yas/configures/WebSecurityConfig.java
Labels: 🔧Refactor

#121 refactor : #118/게시글 조회 응답객체 변경
  src/main/java/org/prgrms/yas/domain/comment/domain/Comment.java
  src/main/java/org/prgrms/yas/domain/comment/repository/CommentRepository.java
  src/main/java/org/prgrms/yas/domain/comment/service/CommentService.java
  src/main/java/org/prgrms/yas/domain/likes/controller/LikesController.java
  src/main/java/org/prgrms/yas/domain/likes/domain/CommentLikes.java
  src/main/java/org/prgrms/yas/domain/likes/dto/LikesDto.java
  src/main/java/org/prgrms/yas/domain/likes/repository/CommentLikesRepository.java
  src/main/java/org/prgrms/yas/domain/likes/repository/PostLikesRepository.java
  src/main/java/org/prgrms/yas/domain/likes/service/LikesService.java
  src/main/java/org/prgrms/yas/domain/post/controller/PostController.java
  src/main/java/org/prgrms/yas/domain/post/dto/CommentDto.java
  src/main/java/org/prgrms/yas/domain/post/dto/PostDetailResponse.java
  src/main/java/org/prgrms/yas/domain/post/dto/RoutineDto.java
  src/main/java/org/prgrms/yas/domain/post/repository/PostRepository.java
  src/main/java/org/prgrms/yas/domain/post/service/PostService.java
  src/main/java/org/prgrms/yas/domain/routine/domain/Routine.java
Labels: 🔧Refactor

#122 [ㄹ좋아요 댓글 ㅊ
  src/main/java/org/prgrms/yas/configures/WebSecurityConfig.java
  src/main/java/org/prgrms/yas/domain/comment/domain/Comment.java
  src/main/java/org/prgrms/yas/domain/comment/repository/CommentRepository.java
  src/main/java/org/prgrms/yas/domain/comment/service/CommentService.java
  src/main/java/org/prgrms/yas/domain/likes/controller/LikesController.java
  src/main/java/org/prgrms/yas/domain/likes/domain/CommentLikes.java
  src/main/java/org/prgrms/yas/domain/likes/domain/PostLikes.java
  src/main/java/org/prgrms/yas/domain/likes/dto/LikesDto.java
  src/main/java/org/prgrms/yas/domain/likes/repository/CommentLikesRepository.java
  src/main/java/org/prgrms/yas/domain/likes/repository/PostLikesRepository.java
  src/main/java/org/prgrms/yas/domain/likes/service/LikesService.java
  src/main/java/org/prgrms/yas/domain/post/controller/PostController.java
  src/main/java/org/prgrms/yas/domain/post/dto/CommentDto.java
  src/main/java/org/prgrms/yas/domain/post/dto/PostDetailResponse.java
  src/main/java/org/prgrms/yas/domain/post/dto/RoutineDto.java
  src/main/java/org/prgrms/yas/domain/post/repository/PostRepository.java
  src/main/java/org/prgrms/yas/domain/post/service/PostService.java
  src/main/java/org/prgrms/yas/domain/routine/domain/Routine.java
  src/main/java/org/prgrms/yas/domain/user/repository/UserRepository.java
Labels: ✨Feature, 🚀Deploy, 🔧Refactor

#125 feat : #117/게시물 최신,인기,나의게시물 조회 기능 추가
  src/main/java/org/prgrms/yas/domain/likes/domain/PostLikes.java
  src/main/java/org/prgrms/yas/domain/likes/dto/LikesResponse.java
  src/main/java/org/prgrms/yas/domain/likes/repository/PostLikesRepository.java
  src/main/java/org/prgrms/yas/domain/post/controller/PostController.java
  src/main/java/org/prgrms/yas/domain/post/domain/RoutinePost.java
  src/main/java/org/prgrms/yas/domain/post/dto/PostListResponse.java
  src/main/java/org/prgrms/yas/domain/post/dto/PostRoutineDto.java
  src/main/java/org/prgrms/yas/domain/post/repository/PostRepository.java
  src/main/java/org/prgrms/yas/domain/post/service/PostService.java
Labels: ✨Feature

#128 Deploy : 게시물 조회 기능 추가
  src/main/java/org/prgrms/yas/domain/likes/domain/PostLikes.java
  src/main/java/org/prgrms/yas/domain/likes/dto/LikesResponse.java
  src/main/java/org/prgrms/yas/domain/likes/repository/PostLikesRepository.java
  src/main/java/org/prgrms/yas/domain/post/controller/PostController.java
  src/main/java/org/prgrms/yas/domain/post/domain/RoutinePost.java
  src/main/java/org/prgrms/yas/domain/post/dto/PostListResponse.java
  src/main/java/org/prgrms/yas/domain/post/dto/PostRoutineDto.java
  src/main/java/org/prgrms/yas/domain/post/repository/PostRepository.java
  src/main/java/org/prgrms/yas/domain/post/service/PostService.java
Labels: ✨Feature, 🚀Deploy

#129 Refactor : OAuth 로그인 수정
  src/main/java/org/prgrms/yas/configures/WebSecurityConfig.java
Labels: 🔧Refactor

#132 fix : #131/타임존 문제 해결
  src/main/java/org/prgrms/yas/YasApplication.java
Labels: 🐞BugFix, ⚙️Setting

#133 Fix : 타임존 오류 해결
  src/main/java/org/prgrms/yas/YasApplication.java
Labels: 🐞BugFix

#134 refactor : #130/루틴 카테고리 종류 추가
  src/main/java/org/prgrms/yas/domain/routine/domain/RoutineCategory.java
Labels: 🔧Refactor

#126 Fix : #124/미션 미조회 수정
  src/main/java/org/prgrms/yas/configures/WebSecurityConfig.java
  src/main/java/org/prgrms/yas/domain/comment/controller/CommentController.java
  src/main/java/org/prgrms/yas/domain/comment/exception/NotFoundCommentException.java
  src/main/java/org/prgrms/yas/domain/mission/controller/MissionController.java
  src/main/java/org/prgrms/yas/domain/mission/controller/MissionStatusController.java
  src/main/java/org/prgrms/yas/domain/mission/domain/Mission.java
  src/main/java/org/prgrms/yas/domain/mission/repository/MissionRepository.java
  src/main/java/org/prgrms/yas/domain/mission/service/MissionService.java
  src/main/java/org/prgrms/yas/domain/mission/service/MissionStatusService.java
  src/main/java/org/prgrms/yas/domain/post/controller/PostController.java
  src/main/java/org/prgrms/yas/domain/post/exception/NotFoundRoutinePostException.java
  src/main/java/org/prgrms/yas/domain/routine/service/RoutineService.java
  src/main/java/org/prgrms/yas/global/error/GlobalExceptionHandler.java
  src/main/java/org/prgrms/yas/global/response/ErrorResponse.java
Labels: 🐞BugFix, 🔧Refactor

#136 Refactor : #127/루틴 객체에 durationGoalTime 변경
  src/main/java/org/prgrms/yas/domain/mission/controller/MissionController.java
  src/main/java/org/prgrms/yas/domain/mission/service/MissionService.java
  src/main/java/org/prgrms/yas/domain/routine/domain/Routine.java
  src/main/java/org/prgrms/yas/domain/routine/dto/RoutineDetailResponse.java
Labels: 🔧Refactor

#120 Refactor : 게시글/댓글 API 수정
  src/main/java/org/prgrms/yas/domain/comment/controller/CommentController.java
  src/main/java/org/prgrms/yas/domain/comment/domain/Comment.java
  src/main/java/org/prgrms/yas/domain/comment/repository/CommentRepository.java
  src/main/java/org/prgrms/yas/domain/comment/service/CommentService.java
  src/main/java/org/prgrms/yas/domain/post/controller/PostController.java
  src/main/java/org/prgrms/yas/domain/post/domain/RoutinePost.java
  src/main/java/org/prgrms/yas/domain/post/dto/RoutineDto.java
  src/main/java/org/prgrms/yas/domain/post/exception/DuplicatePostException.java
  src/main/java/org/prgrms/yas/domain/post/exception/WrongUserException.java
  src/main/java/org/prgrms/yas/domain/post/repository/PostRepository.java
  src/main/java/org/prgrms/yas/domain/post/service/PostService.java
  src/main/java/org/prgrms/yas/domain/routine/repository/RoutineRepository.java
Labels: 🔧Refactor

#140 Refactor : #139/Post 관련 문제 해결
  src/main/java/org/prgrms/yas/configures/WebConfig.java
  src/main/java/org/prgrms/yas/configures/WebSecurityConfig.java
  src/main/java/org/prgrms/yas/domain/likes/repository/PostLikesRepository.java
  src/main/java/org/prgrms/yas/domain/mission/service/MissionService.java
  src/main/java/org/prgrms/yas/domain/post/controller/PostController.java
  src/main/java/org/prgrms/yas/domain/post/domain/RoutinePost.java
  src/main/java/org/prgrms/yas/domain/post/repository/PostRepository.java
Labels: 🐞BugFix, 🔧Refactor

#141 Refactor : #139/응답객체 필드 추가
  src/main/java/org/prgrms/yas/domain/post/dto/PostListResponse.java
  src/main/java/org/prgrms/yas/domain/post/dto/PostRoutineDto.java
  src/main/java/org/prgrms/yas/domain/post/dto/WeekDto.java
Labels: 🔧Refactor

#138 Refactor : #135/게시물 내용 작성 기능 추가
  src/main/java/org/prgrms/yas/domain/likes/repository/PostLikesRepository.java
  src/main/java/org/prgrms/yas/domain/post/controller/PostController.java
  src/main/java/org/prgrms/yas/domain/post/domain/RoutinePost.java
  src/main/java/org/prgrms/yas/domain/post/dto/PostCreateRequest.java
  src/main/java/org/prgrms/yas/domain/post/dto/PostDetailResponse.java
  src/main/java/org/prgrms/yas/domain/post/dto/PostListResponse.java
  src/main/java/org/prgrms/yas/domain/post/repository/PostRepository.java
  src/main/java/org/prgrms/yas/domain/post/service/PostService.java
  src/main/java/org/prgrms/yas/domain/routine/dto/RoutineListResponse.java
Labels: ✨Feature

#143 deploy : post 관련 API 배포
  src/main/java/org/prgrms/yas/configures/WebConfig.java
  src/main/java/org/prgrms/yas/configures/WebSecurityConfig.java
  src/main/java/org/prgrms/yas/domain/comment/controller/CommentController.java
  src/main/java/org/prgrms/yas/domain/comment/domain/Comment.java
  src/main/java/org/prgrms/yas/domain/comment/exception/NotFoundCommentException.java
  src/main/java/org/prgrms/yas/domain/comment/repository/CommentRepository.java
  src/main/java/org/prgrms/yas/domain/comment/service/CommentService.java
  src/main/java/org/prgrms/yas/domain/likes/repository/PostLikesRepository.java
  src/main/java/org/prgrms/yas/domain/mission/controller/MissionController.java
  src/main/java/org/prgrms/yas/domain/mission/controller/MissionStatusController.java
  src/main/java/org/prgrms/yas/domain/mission/domain/Mission.java
  src/main/java/org/prgrms/yas/domain/mission/repository/MissionRepository.java
  src/main/java/org/prgrms/yas/domain/mission/service/MissionService.java
  src/main/java/org/prgrms/yas/domain/mission/service/MissionStatusService.java
  src/main/java/org/prgrms/yas/domain/post/controller/PostController.java
  src/main/java/org/prgrms/yas/domain/post/domain/RoutinePost.java
  src/main/java/org/prgrms/yas/domain/post/dto/PostCreateRequest.java
  src/main/java/org/prgrms/yas/domain/post/dto/PostDetailResponse.java
  src/main/java/org/prgrms/yas/domain/post/dto/PostListResponse.java
  src/main/java/org/prgrms/yas/domain/post/dto/PostRoutineDto.java
  src/main/java/org/prgrms/yas/domain/post/dto/RoutineDto.java
  src/main/java/org/prgrms/yas/domain/post/dto/WeekDto.java
  src/main/java/org/prgrms/yas/domain/post/exception/DuplicatePostException.java
  src/main/java/org/prgrms/yas/domain/post/exception/NotFoundRoutinePostException.java
  src/main/java/org/prgrms/yas/domain/post/exception/WrongUserException.java
  src/main/java/org/prgrms/yas/domain/post/repository/PostRepository.java
  src/main/java/org/prgrms/yas/domain/post/service/PostService.java
  src/main/java/org/prgrms/yas/domain/routine/domain/Routine.java
  src/main/java/org/prgrms/yas/domain/routine/domain/RoutineCategory.java
  src/main/java/org/prgrms/yas/domain/routine/dto/RoutineDetailResponse.java
  src/main/java/org/prgrms/yas/domain/routine/dto/RoutineListResponse.java
  src/main/java/org/prgrms/yas/domain/routine/repository/RoutineRepository.java
  src/main/java/org/prgrms/yas/domain/routine/service/RoutineService.java
  src/main/java/org/prgrms/yas/global/error/GlobalExceptionHandler.java
  src/main/java/org/prgrms/yas/global/response/ErrorResponse.java
Labels: 🚀Deploy

#144 chore : 배포 관련 동기화
  src/main/java/org/prgrms/yas/configures/WebSecurityConfig.java
Labels: ⚙️Setting, 🔧Refactor

#145 fix : RoutineController 수정
  src/main/java/org/prgrms/yas/domain/post/controller/PostController.java
Labels: 🐞BugFix, 🔧Refactor

#149 feat : #147/루틴 조회시 삭제된 데이터 조회 안되게 변경
  src/main/java/org/prgrms/yas/domain/mission/repository/MissionRepository.java
  src/main/java/org/prgrms/yas/domain/mission/service/MissionService.java
  src/main/java/org/prgrms/yas/domain/routine/domain/Routine.java
  src/main/java/org/prgrms/yas/domain/routine/repository/RoutineRepository.java
  src/main/java/org/prgrms/yas/domain/routine/service/RoutineService.java
Labels: 🔧Refactor

#150 Refactor : 포스트에서 루틴가져오기 기능 추가, 루틴 삭제 조회 수정
  src/main/java/org/prgrms/yas/domain/mission/repository/MissionRepository.java
  src/main/java/org/prgrms/yas/domain/mission/service/MissionService.java
  src/main/java/org/prgrms/yas/domain/routine/controller/RoutineController.java
  src/main/java/org/prgrms/yas/domain/routine/domain/Routine.java
  src/main/java/org/prgrms/yas/domain/routine/dto/RoutineDetailCreateRequest.java
  src/main/java/org/prgrms/yas/domain/routine/repository/RoutineRepository.java
  src/main/java/org/prgrms/yas/domain/routine/service/RoutineService.java
Labels: 🐞BugFix, 🔧Refactor

#154 feat : #153/루틴 상세 조회시 미션 수정
  src/main/java/org/prgrms/yas/domain/mission/repository/MissionRepository.java
  src/main/java/org/prgrms/yas/domain/routine/domain/Routine.java
  src/main/java/org/prgrms/yas/domain/routine/service/RoutineService.java
Labels: 🐞BugFix

#155 [Fix] 루틴 상세 조회시 미션 수정
  src/main/java/org/prgrms/yas/domain/mission/repository/MissionRepository.java
  src/main/java/org/prgrms/yas/domain/routine/domain/Routine.java
  src/main/java/org/prgrms/yas/domain/routine/service/RoutineService.java
Labels: 🐞BugFix

#158 Fix : 타임존 시간 수정
  src/main/java/org/prgrms/yas/domain/routine/dto/RoutineCreateRequest.java
  src/main/java/org/prgrms/yas/domain/routine/dto/RoutineDetailCreateRequest.java
  src/main/java/org/prgrms/yas/domain/routine/dto/RoutineDetailResponse.java
  src/main/java/org/prgrms/yas/domain/routine/dto/RoutineListResponse.java
Labels: 🐞BugFix

#159 deploy : 타임존 관련 시간 수정
  src/main/java/org/prgrms/yas/domain/routine/dto/RoutineCreateRequest.java
  src/main/java/org/prgrms/yas/domain/routine/dto/RoutineDetailCreateRequest.java
  src/main/java/org/prgrms/yas/domain/routine/dto/RoutineDetailResponse.java
  src/main/java/org/prgrms/yas/domain/routine/dto/RoutineListResponse.java
Labels: 🐞BugFix, 🚀Deploy

#161 Chore : 불필요한 파일 삭제
  build.gradle
  src/main/java/org/prgrms/yas/configures/WebSecurityConfig.java
  src/main/java/org/prgrms/yas/domain/user/service/OAuth2UserService.java
  src/main/java/org/prgrms/yas/oauth2/OAuth2AuthenticationSuccessHandler.java
  src/main/resources/application-local.yml
  src/test/java/org/prgrms/yas/ApplicationTest.java
  src/test/java/org/prgrms/yas/config/TestConfig.java
  src/test/java/org/prgrms/yas/config/WithMockJwtAuthentication.java
  src/test/java/org/prgrms/yas/config/WithMockJwtAuthenticationSecurityContextFactory.java
  src/test/java/org/prgrms/yas/domain/user/controller/UserControllerTest.java
  src/test/java/org/prgrms/yas/domain/user/dto/UserSignInTestRequest.java
  src/test/java/org/prgrms/yas/domain/user/dto/UserSignUpTestRequest.java
Labels: 🔧Refactor

#162 deploy : Oauth2 설정 파일 삭제
  build.gradle
  src/main/java/org/prgrms/yas/configures/WebSecurityConfig.java
  src/main/java/org/prgrms/yas/domain/user/service/OAuth2UserService.java
  src/main/java/org/prgrms/yas/oauth2/OAuth2AuthenticationSuccessHandler.java
  src/main/resources/application-local.yml
  src/test/java/org/prgrms/yas/ApplicationTest.java
  src/test/java/org/prgrms/yas/config/TestConfig.java
  src/test/java/org/prgrms/yas/config/WithMockJwtAuthentication.java
  src/test/java/org/prgrms/yas/config/WithMockJwtAuthenticationSecurityContextFactory.java
  src/test/java/org/prgrms/yas/domain/user/controller/UserControllerTest.java
  src/test/java/org/prgrms/yas/domain/user/dto/UserSignInTestRequest.java
  src/test/java/org/prgrms/yas/domain/user/dto/UserSignUpTestRequest.java
Labels: 🚀Deploy, 🔧Refactor

#163 Chore : 불필요한 파일 삭제
  src/test/java/org/prgrms/yas/ApplicationTest.java
  src/test/java/org/prgrms/yas/config/TestConfig.java
  src/test/java/org/prgrms/yas/config/WithMockJwtAuthentication.java
  src/test/java/org/prgrms/yas/config/WithMockJwtAuthenticationSecurityContextFactory.java
  src/test/java/org/prgrms/yas/domain/user/controller/UserControllerTest.java
  src/test/java/org/prgrms/yas/domain/user/dto/UserSignInTestRequest.java
  src/test/java/org/prgrms/yas/domain/user/dto/UserSignUpTestRequest.java
Labels: 🔧Refactor

#164 deploy : 불필요한 파일 삭제
  src/test/java/org/prgrms/yas/ApplicationTest.java
  src/test/java/org/prgrms/yas/config/TestConfig.java
  src/test/java/org/prgrms/yas/config/WithMockJwtAuthentication.java
  src/test/java/org/prgrms/yas/config/WithMockJwtAuthenticationSecurityContextFactory.java
  src/test/java/org/prgrms/yas/domain/user/controller/UserControllerTest.java
  src/test/java/org/prgrms/yas/domain/user/dto/UserSignInTestRequest.java
  src/test/java/org/prgrms/yas/domain/user/dto/UserSignUpTestRequest.java
Labels: 🚀Deploy

#171 feat : #168/ 미션 상태 조회시 응답객체에 userDurationTime 추가
  src/main/java/org/prgrms/yas/domain/mission/domain/MissionStatus.java
  src/main/java/org/prgrms/yas/domain/mission/dto/MissionStatusDetailResponse.java
Labels: 🐞BugFix

#169 Fix : 게시물 단건조회의 응답객체 변경
  src/main/java/org/prgrms/yas/domain/post/dto/PostDetailResponse.java
  src/main/java/org/prgrms/yas/domain/post/service/PostService.java
Labels: 🐞BugFix

#166 fix : #165/좋아요 로직 수정
  src/main/java/org/prgrms/yas/domain/likes/repository/CommentLikesRepository.java
  src/main/java/org/prgrms/yas/domain/likes/repository/PostLikesRepository.java
  src/main/java/org/prgrms/yas/domain/likes/service/LikesService.java
Labels: 🐞BugFix

#172 fix : 게시물, 좋아요, 미션 관련 수정
  src/main/java/org/prgrms/yas/domain/likes/repository/CommentLikesRepository.java
  src/main/java/org/prgrms/yas/domain/likes/repository/PostLikesRepository.java
  src/main/java/org/prgrms/yas/domain/likes/service/LikesService.java
  src/main/java/org/prgrms/yas/domain/mission/domain/MissionStatus.java
  src/main/java/org/prgrms/yas/domain/mission/dto/MissionStatusDetailResponse.java
  src/main/java/org/prgrms/yas/domain/post/dto/PostDetailResponse.java
  src/main/java/org/prgrms/yas/domain/post/service/PostService.java
Labels: 🚀Deploy

#174 fix : #173/게시물 생성 DTO 수정
  src/main/java/org/prgrms/yas/domain/post/dto/PostCreateRequest.java
Labels: 🐞BugFix

#175 fix : 게시글 등록 시 파싱 에러 수정
  src/main/java/org/prgrms/yas/domain/post/dto/PostCreateRequest.java
Labels: 🐞BugFix, 🚀Deploy

#177 Fix : 게시물 삭제 메소드 수정
  src/main/java/org/prgrms/yas/domain/post/service/PostService.java
Labels: 🐞BugFix, 🔧Refactor

#178 fix : 게시물 삭제 메소드 수정
  src/main/java/org/prgrms/yas/domain/post/service/PostService.java
Labels: 🐞BugFix, 🚀Deploy

#180 feat : #179/게시글 조회시 중복되는 값 제거
  src/main/java/org/prgrms/yas/domain/post/repository/PostRepository.java
Labels: 🐞BugFix

#181 fix : 게시물 조회시 중복되는 문제 해결
  src/main/java/org/prgrms/yas/domain/post/repository/PostRepository.java
Labels: 🐞BugFix, 🚀Deploy

#183 feat : #182/게시물 단건 조회시 응답객체에 필드 추가
  src/main/java/org/prgrms/yas/domain/post/dto/RoutineDto.java
Labels: 🔧Refactor

#185 refactor : 게시물 단건 조회시 응답객체에 필드 추가
  src/main/java/org/prgrms/yas/domain/post/dto/RoutineDto.java
Labels: 🔧Refactor

#186 refactor : #184/루틴조회시 반환객체에 포스팅되었는지 확인하는 필드 추가
  src/main/java/org/prgrms/yas/domain/mission/domain/Mission.java
  src/main/java/org/prgrms/yas/domain/mission/repository/MissionRepository.java
  src/main/java/org/prgrms/yas/domain/mission/service/MissionService.java
  src/main/java/org/prgrms/yas/domain/post/service/PostService.java
  src/main/java/org/prgrms/yas/domain/routine/domain/Routine.java
  src/main/java/org/prgrms/yas/domain/routine/dto/RoutineDetailResponse.java
  src/main/java/org/prgrms/yas/domain/routine/dto/RoutineListResponse.java
Labels: 🔧Refactor

#187 refactor : 루틴조회시 반환객체에 포스팅되었는지 확인하는 필드 추가
  src/main/java/org/prgrms/yas/domain/mission/domain/Mission.java
  src/main/java/org/prgrms/yas/domain/mission/repository/MissionRepository.java
  src/main/java/org/prgrms/yas/domain/mission/service/MissionService.java
  src/main/java/org/prgrms/yas/domain/post/service/PostService.java
  src/main/java/org/prgrms/yas/domain/routine/domain/Routine.java
  src/main/java/org/prgrms/yas/domain/routine/dto/RoutineDetailResponse.java
  src/main/java/org/prgrms/yas/domain/routine/dto/RoutineListResponse.java
Labels: 🚀Deploy, 🔧Refactor

#189 feat : #188/게시판에서 루틴 가져올때 오류 해결
  src/main/java/org/prgrms/yas/domain/routine/controller/RoutineController.java
Labels: 🐞BugFix

#190 fix : 게시판에서 루틴 가져올때 오류 해결
  src/main/java/org/prgrms/yas/domain/routine/controller/RoutineController.java
Labels: 🐞BugFix, 🚀Deploy

#192 fix : #191/미션 순서 변경시 생기는 오류 수정
  src/main/java/org/prgrms/yas/domain/mission/repository/MissionRepository.java
  src/main/java/org/prgrms/yas/domain/mission/service/MissionService.java
Labels: 🐞BugFix

#196 chore : #195/jwt 토큰 유효시간 변경
  src/main/resources/application-local.yml
Labels: 📌Chore

#198 fix : 삭제된 게시물 조회 수정
  src/main/java/org/prgrms/yas/domain/post/service/PostService.java
Labels: 🐞BugFix

#199 fix : 게시물 조회 및 jwt 토큰 수정
  src/main/java/org/prgrms/yas/domain/post/service/PostService.java
  src/main/resources/application-local.yml
Labels: 🐞BugFix, 🚀Deploy, 📌Chore

#205 Fix : nginx 스크립트 추가
  appspec.yml
  scripts/health_check.sh
  scripts/run_new_was.sh
  scripts/switch.sh
Labels: ✨Feature, 🚀Deploy, ⚙️Setting

#206 Test : nginx 서버 실행 확인
  src/main/java/org/prgrms/yas/domain/user/controller/UserController.java
Labels: 🚀Deploy, 📌Chore

#201 Fix : #200/삭제된 게시물 조회 에러 수정
  src/main/java/org/prgrms/yas/domain/post/repository/PostRepository.java
  src/main/java/org/prgrms/yas/domain/routine/domain/Routine.java
  src/main/java/org/prgrms/yas/domain/routine/dto/RoutineCreateRequest.java
  src/main/java/org/prgrms/yas/domain/routine/dto/RoutineDetailCreateRequest.java
  src/main/java/org/prgrms/yas/domain/routine/service/RoutineService.java
Labels: 🐞BugFix

#204 fix : 시간 타입 관련 메소드 수정
  src/main/java/org/prgrms/yas/domain/comment/controller/CommentController.java
  src/main/java/org/prgrms/yas/domain/likes/controller/LikesController.java
  src/main/java/org/prgrms/yas/domain/mission/dto/MissionCreateRequest.java
  src/main/java/org/prgrms/yas/domain/mission/dto/MissionDetailResponse.java
  src/main/java/org/prgrms/yas/domain/mission/dto/MissionStatusDetailResponse.java
  src/main/java/org/prgrms/yas/domain/mission/dto/MissionStatusUpdateRequest.java
  src/main/java/org/prgrms/yas/domain/post/controller/PostController.java
  src/main/java/org/prgrms/yas/domain/post/dto/CommentDto.java
  src/main/java/org/prgrms/yas/domain/post/dto/PostDetailResponse.java
  src/main/java/org/prgrms/yas/domain/post/dto/PostListResponse.java
  src/main/java/org/prgrms/yas/domain/post/dto/PostRoutineDto.java
  src/main/java/org/prgrms/yas/domain/post/dto/RoutineDto.java
  src/main/java/org/prgrms/yas/domain/routine/dto/RoutineDetailCreateRequest.java
  src/main/java/org/prgrms/yas/domain/routine/dto/RoutineDetailResponse.java
  src/main/java/org/prgrms/yas/domain/routine/dto/RoutineListResponse.java
  src/main/java/org/prgrms/yas/domain/routine/dto/RoutineUpdateResponse.java
Labels: 🐞BugFix, 📌Chore

#211 fix : 시간 패턴 수정
  src/main/java/org/prgrms/yas/domain/comment/controller/CommentController.java
  src/main/java/org/prgrms/yas/domain/likes/controller/LikesController.java
  src/main/java/org/prgrms/yas/domain/mission/dto/MissionCreateRequest.java
  src/main/java/org/prgrms/yas/domain/mission/dto/MissionDetailResponse.java
  src/main/java/org/prgrms/yas/domain/mission/dto/MissionStatusDetailResponse.java
  src/main/java/org/prgrms/yas/domain/mission/dto/MissionStatusUpdateRequest.java
  src/main/java/org/prgrms/yas/domain/post/controller/PostController.java
  src/main/java/org/prgrms/yas/domain/post/dto/CommentDto.java
  src/main/java/org/prgrms/yas/domain/post/dto/PostDetailResponse.java
  src/main/java/org/prgrms/yas/domain/post/dto/PostListResponse.java
  src/main/java/org/prgrms/yas/domain/post/dto/PostRoutineDto.java
  src/main/java/org/prgrms/yas/domain/post/dto/RoutineDto.java
  src/main/java/org/prgrms/yas/domain/routine/dto/RoutineDetailCreateRequest.java
  src/main/java/org/prgrms/yas/domain/routine/dto/RoutineDetailResponse.java
  src/main/java/org/prgrms/yas/domain/routine/dto/RoutineListResponse.java
  src/main/java/org/prgrms/yas/domain/routine/dto/RoutineUpdateResponse.java
Labels: 🐞BugFix, 📌Chore

#213 feat : #210/스케쥴러 메소드 구현
  appspec.yml
  scripts/health_check.sh
  scripts/run_new_was.sh
  scripts/switch.sh
  src/main/java/org/prgrms/yas/YasApplication.java
  src/main/java/org/prgrms/yas/domain/comment/repository/CommentRepository.java
  src/main/java/org/prgrms/yas/domain/user/controller/TestController.java
  src/main/java/org/prgrms/yas/domain/user/repository/UserRepository.java
  src/main/java/org/prgrms/yas/global/scheduler/ScheduledService.java
  src/main/resources/application-local.yml
Labels: ✨Feature

#215 refactor : #214/게시물 삭제 방식 수정
  src/main/java/org/prgrms/yas/domain/likes/service/LikesService.java
  src/main/java/org/prgrms/yas/domain/post/domain/RoutinePost.java
  src/main/java/org/prgrms/yas/domain/post/repository/PostRepository.java
  src/main/java/org/prgrms/yas/domain/post/service/PostService.java
  src/main/java/org/prgrms/yas/domain/routine/repository/RoutineRepository.java
  src/main/java/org/prgrms/yas/domain/user/controller/TestController.java
  src/main/resources/application-local.yml
Labels: 🔧Refactor

#217 chore : #216/불필요한 파일 삭제
  appspec.yml
  scripts/health_check.sh
  scripts/run_new_was.sh
  scripts/switch.sh
  src/main/java/org/prgrms/yas/YasApplication.java
  src/main/java/org/prgrms/yas/configures/WebSecurityConfig.java
  src/main/java/org/prgrms/yas/domain/comment/service/CommentService.java
  src/main/java/org/prgrms/yas/global/exception/NotFoundException.java
  src/main/resources/application-prod.yml
Labels: 📌Chore

#218 deploy : 수정 이후 중간 배포
  appspec.yml
  src/main/java/org/prgrms/yas/YasApplication.java
  src/main/java/org/prgrms/yas/configures/WebSecurityConfig.java
  src/main/java/org/prgrms/yas/domain/comment/repository/CommentRepository.java
  src/main/java/org/prgrms/yas/domain/comment/service/CommentService.java
  src/main/java/org/prgrms/yas/domain/likes/service/LikesService.java
  src/main/java/org/prgrms/yas/domain/post/domain/RoutinePost.java
  src/main/java/org/prgrms/yas/domain/post/repository/PostRepository.java
  src/main/java/org/prgrms/yas/domain/post/service/PostService.java
  src/main/java/org/prgrms/yas/domain/routine/repository/RoutineRepository.java
  src/main/java/org/prgrms/yas/domain/user/repository/UserRepository.java
  src/main/java/org/prgrms/yas/global/exception/NotFoundException.java
  src/main/java/org/prgrms/yas/global/scheduler/ScheduledService.java
  src/main/resources/application-prod.yml
Labels: 🚀Deploy, 📌Chore

#219 fix : #212/타임존 문제 해결
  src/main/java/org/prgrms/yas/domain/BaseEntity.java
  src/main/java/org/prgrms/yas/domain/mission/domain/MissionStatus.java
  src/main/java/org/prgrms/yas/domain/mission/dto/MissionStatusDetailResponse.java
  src/main/java/org/prgrms/yas/domain/mission/dto/MissionStatusUpdateRequest.java
  src/main/java/org/prgrms/yas/domain/mission/service/MissionStatusService.java
  src/main/java/org/prgrms/yas/domain/post/controller/PostController.java
  src/main/java/org/prgrms/yas/domain/post/dto/CommentDto.java
  src/main/java/org/prgrms/yas/domain/post/dto/PostListResponse.java
  src/main/java/org/prgrms/yas/domain/post/dto/PostRoutineDto.java
  src/main/java/org/prgrms/yas/domain/post/dto/RoutineDto.java
  src/main/java/org/prgrms/yas/domain/routine/controller/RoutineController.java
  src/main/java/org/prgrms/yas/domain/routine/domain/Routine.java
  src/main/java/org/prgrms/yas/domain/routine/domain/RoutineStatus.java
  src/main/java/org/prgrms/yas/domain/routine/dto/RoutineCreateRequest.java
  src/main/java/org/prgrms/yas/domain/routine/dto/RoutineDetailCreateRequest.java
  src/main/java/org/prgrms/yas/domain/routine/dto/RoutineDetailResponse.java
  src/main/java/org/prgrms/yas/domain/routine/dto/RoutineListResponse.java
  src/main/java/org/prgrms/yas/domain/routine/dto/RoutineUpdateResponse.java
  src/main/java/org/prgrms/yas/domain/routine/service/RoutineService.java
  src/main/java/org/prgrms/yas/domain/routine/service/Status.java
Labels: 🐞BugFix

#221 chore : Main과 Develop 브랜치 동기화
  scripts/deploy.sh
  src/main/java/org/prgrms/yas/configures/WebSecurityConfig.java
Labels: 📌Chore

#222 Fix : BaseEntity 시간 에러 수정
  src/main/java/org/prgrms/yas/YasApplication.java
  src/main/java/org/prgrms/yas/configures/WebSecurityConfig.java
Labels: 🐞BugFix

#223 deploy : BaseEntity 타입 에러 수정
  src/main/java/org/prgrms/yas/YasApplication.java
  src/main/java/org/prgrms/yas/configures/WebSecurityConfig.java
Labels: 🐞BugFix, 🚀Deploy

#224 style : readme 수정
  README.md
Labels: 👔Style

#227 refactor : #226/ 카테고리 종류 추가
  src/main/java/org/prgrms/yas/domain/routine/domain/RoutineCategory.java
Labels: 🔧Refactor

#228 refactor : #develop/루틴 카테고리 종류 추가
  README.md
  src/main/java/org/prgrms/yas/domain/routine/domain/RoutineCategory.java
Labels: 🚀Deploy, 🔧Refactor

#231 Fix : #230/Calendar 클래스 타임존 변경
  src/main/java/org/prgrms/yas/domain/routine/service/RoutineService.java
Labels: 🐞BugFix

#232 fix : Calendar 타임존 변경
  src/main/java/org/prgrms/yas/domain/routine/service/RoutineService.java
Labels: 🐞BugFix

#235 hotfix : #234/게시물 삭제간 댓글로 인한 에러 해결
  src/main/java/org/prgrms/yas/domain/comment/domain/Comment.java
  src/main/java/org/prgrms/yas/domain/post/domain/RoutinePost.java
Labels: 🐞BugFix, 🚀Deploy

#236 Hotfix : 게시물 삭제간 에러 해결
  src/main/java/org/prgrms/yas/domain/comment/domain/Comment.java
  src/main/java/org/prgrms/yas/domain/post/domain/RoutinePost.java
Labels: 🐞BugFix, 🚀Deploy

#237 Hotfix : 댓글 좋아요와 게시물 관계 수정
  src/main/java/org/prgrms/yas/domain/comment/domain/Comment.java
  src/main/java/org/prgrms/yas/domain/likes/domain/CommentLikes.java
  src/main/java/org/prgrms/yas/domain/likes/repository/CommentLikesRepository.java
  src/main/java/org/prgrms/yas/domain/post/service/PostService.java
Labels: 🐞BugFix, 🚀Deploy
