Repository prgrms-web-devcourse/Team_WAS_YAS_BE, pull requests merged in 2022-02, with the labels that each got.

#194 test : #194/회원통합테스트 구현
  build.gradle
  src/main/java/org/prgrms/yas/configures/WebSecurityConfig.java
  src/main/java/org/prgrms/yas/domain/user/domain/Role.java
  src/main/java/org/prgrms/yas/domain/user/dto/UserSignUpRequest.java
  src/main/java/org/prgrms/yas/domain/user/dto/UserUpdateRequest.java
  src/main/java/org/prgrms/yas/jwt/JwtAuthenticationToken.java
  src/test/java/org/prgrms/yas/config/TestConfig.java
  src/test/java/org/prgrms/yas/config/WithMockJwtAuthentication.java
  src/test/java/org/prgrms/yas/config/WithMockJwtAuthenticationSecurityContextFactory.java
  src/test/java/org/prgrms/yas/domain/user/controller/UserControllerTest.java
  src/test/resources/application.yml
Labels: ✅Test

#292 deploy : 회원 통합 테스트 추가
  build.gradle
  src/main/java/org/prgrms/yas/configures/WebSecurityConfig.java
  src/main/java/org/prgrms/yas/domain/user/domain/Role.java
  src/main/java/org/prgrms/yas/domain/user/dto/UserSignUpRequest.java
  src/main/java/org/prgrms/yas/domain/user/dto/UserUpdateRequest.java
  src/main/java/org/prgrms/yas/jwt/JwtAuthenticationToken.java
  src/test/java/org/prgrms/yas/config/TestConfig.java
  src/test/java/org/prgrms/yas/config/WithMockJwtAuthentication.java
  src/test/java/org/prgrms/yas/config/WithMockJwtAuthenticationSecurityContextFactory.java
  src/test/java/org/prgrms/yas/domain/user/controller/UserControllerTest.java
  src/test/resources/application.yml
Labels: ✅Test

#294 Fix : 소셜 로그인 관련 회원 통합 테스트 코드 설정 파일 수정
  src/test/java/org/prgrms/yas/config/WithMockJwtAuthentication.java
  src/test/java/org/prgrms/yas/config/WithMockJwtAuthenticationSecurityContextFactory.java
  src/test/resources/application.yml
Labels: 🐞BugFix

#295 deploy : 회원 테스트 코드 관련 에러 수정 배포
  src/test/java/org/prgrms/yas/config/WithMockJwtAuthentication.java
  src/test/java/org/prgrms/yas/config/WithMockJwtAuthenticationSecurityContextFactory.java
  src/test/resources/application.yml
Labels: 🐞BugFix, 🚀Deploy

#299 Refactor : #297/미션상태 상세조회시 routineStatusId 추가
  src/main/java/org/prgrms/yas/domain/mission/domain/Mission.java
  src/main/java/org/prgrms/yas/domain/mission/dto/MissionDetailStatusResponse.java
  src/main/java/org/prgrms/yas/domain/mission/service/MissionStatusService.java
  src/main/java/org/prgrms/yas/domain/routine/service/RoutineStatusService.java
Labels: 🔧Refactor

#290 Refactor : #285/루틴 후기 등록 오류 해결
  src/main/java/org/prgrms/yas/domain/mission/service/MissionStatusService.java
Labels: 🔧Refactor

#301 Fix : #300/루틴완료 조회시 타임존 오류 수정
  src/main/java/org/prgrms/yas/domain/mission/domain/MissionStatus.java
  src/main/java/org/prgrms/yas/domain/mission/service/MissionStatusService.java
  src/main/java/org/prgrms/yas/domain/routine/domain/RoutineStatus.java
  src/main/java/org/prgrms/yas/domain/routine/dto/RoutineStatusDetailResponse.java
  src/main/java/org/prgrms/yas/domain/routine/dto/RoutineStatusListResponse.java
Labels: 🐞BugFix

#302 Refactor : #develop/routineStatus 관련 리팩토링
  src/main/java/org/prgrms/yas/domain/mission/domain/Mission.java
  src/main/java/org/prgrms/yas/domain/mission/domain/MissionStatus.java
  src/main/java/org/prgrms/yas/domain/mission/dto/MissionDetailStatusResponse.java
  src/main/java/org/prgrms/yas/domain/mission/service/MissionStatusService.java
  src/main/java/org/prgrms/yas/domain/routine/domain/RoutineStatus.java
  src/main/java/org/prgrms/yas/domain/routine/dto/RoutineStatusDetailResponse.java
  src/main/java/org/prgrms/yas/domain/routine/dto/RoutineStatusListResponse.java
  src/main/java/org/prgrms/yas/domain/routine/service/RoutineStatusService.java
Labels: 🐞BugFix, 🚀Deploy, 🔧Refactor

#289 Feat : #284/회원탈퇴 기능 추가
  src/main/java/org/prgrms/yas/domain/comment/domain/Comment.java
  src/main/java/org/prgrms/yas/domain/comment/repository/CommentRepository.java
  src/main/java/org/prgrms/yas/domain/comment/service/CommentService.java
  src/main/java/org/prgrms/yas/domain/likes/repository/CommentLikesRepository.java
  src/main/java/org/prgrms/yas/domain/likes/repository/PostLikesRepository.java
  src/main/java/org/prgrms/yas/domain/mission/domain/Mission.java
  src/main/java/org/prgrms/yas/domain/mission/service/MissionService.java
  src/main/java/org/prgrms/yas/domain/routine/domain/Routine.java
  src/main/java/org/prgrms/yas/domain/routine/domain/RoutineStatus.java
  src/main/java/org/prgrms/yas/domain/routine/repository/RoutineRepository.java
  src/main/java/org/prgrms/yas/domain/routine/repository/RoutineStatusImageRepository.java
  src/main/java/org/prgrms/yas/domain/routine/repository/RoutineStatusRepository.java
  src/main/java/org/prgrms/yas/domain/user/controller/UserController.java
  src/main/java/org/prgrms/yas/domain/user/domain/User.java
  src/main/java/org/prgrms/yas/domain/user/dto/UserPasswordChangeRequest.java
  src/main/java/org/prgrms/yas/domain/user/dto/UserPasswordRequest.java
  src/main/java/org/prgrms/yas/domain/user/repository/UserRepository.java
  src/main/java/org/prgrms/yas/domain/user/service/UserService.java
  src/main/java/org/prgrms/yas/global/scheduler/ScheduledService.java
Labels: ✨Feature, 🔧Refactor, 📌Chore

#303 deploy : #284/회원탈퇴 기능 추가
  src/main/java/org/prgrms/yas/domain/comment/domain/Comment.java
  src/main/java/org/prgrms/yas/domain/comment/repository/CommentRepository.java
  src/main/java/org/prgrms/yas/domain/comment/service/CommentService.java
  src/main/java/org/prgrms/yas/domain/likes/repository/CommentLikesRepository.java
  src/main/java/org/prgrms/yas/domain/likes/repository/PostLikesRepository.java
  src/main/java/org/prgrms/yas/domain/mission/domain/Mission.java
  src/main/java/org/prgrms/yas/domain/mission/service/MissionService.java
  src/main/java/org/prgrms/yas/domain/routine/domain/Routine.java
  src/main/java/org/prgrms/yas/domain/routine/domain/RoutineStatus.java
  src/main/java/org/prgrms/yas/domain/routine/repository/RoutineRepository.java
  src/main/java/org/prgrms/yas/domain/routine/repository/RoutineStatusImageRepository.java
  src/main/java/org/prgrms/yas/domain/routine/repository/RoutineStatusRepository.java
  src/main/java/org/prgrms/yas/domain/user/controller/UserController.java
  src/main/java/org/prgrms/yas/domain/user/domain/User.java
  src/main/java/org/prgrms/yas/domain/user/dto/UserPasswordChangeRequest.java
  src/main/java/org/prgrms/yas/domain/user/dto/UserPasswordRequest.java
  src/main/java/org/prgrms/yas/domain/user/repository/UserRepository.java
  src/main/java/org/prgrms/yas/domain/user/service/UserService.java
  src/main/java/org/prgrms/yas/global/scheduler/ScheduledService.java
Labels: ✨Feature, 🚀Deploy, 🔧Refactor

#305 Feat : #296/회원 탈퇴 기능 및 에러 수정
  src/main/java/org/prgrms/yas/domain/mission/repository/MissionRepository.java
  src/main/java/org/prgrms/yas/domain/post/repository/PostRepository.java
  src/test/java/org/prgrms/yas/domain/user/controller/UserControllerTest.java
Labels: 🐞BugFix, 🚀Deploy

#306 deploy : 회원탈퇴기능 에러 수정
  src/main/java/org/prgrms/yas/domain/mission/repository/MissionRepository.java
  src/main/java/org/prgrms/yas/domain/post/repository/PostRepository.java
  src/test/java/org/prgrms/yas/domain/user/controller/UserControllerTest.java
Labels: 🚀Deploy

#308 Fix : #307/테스트 관련 Dto 수정
  src/main/java/org/prgrms/yas/domain/user/dto/UserPasswordChangeRequest.java
  src/main/java/org/prgrms/yas/domain/user/dto/UserPasswordRequest.java
  src/test/java/org/prgrms/yas/domain/user/controller/UserControllerTest.java
Labels: 🐞BugFix

#310 deploy : 회원 비밀번호 Dto 에러 수정
  src/main/java/org/prgrms/yas/domain/user/dto/UserPasswordChangeRequest.java
  src/main/java/org/prgrms/yas/domain/user/dto/UserPasswordRequest.java
  src/test/java/org/prgrms/yas/domain/user/controller/UserControllerTest.java
Labels: 🐞BugFix, 🚀Deploy

#313 Fix : #311/완료한 루틴 진행시 생기는 타임존 문제 해결
  src/main/java/org/prgrms/yas/domain/routine/service/Status.java
Labels: 🐞BugFix

#314 Fix : #develp/완료한 루틴 진행시 생기는 타임존 문제 해결
  src/main/java/org/prgrms/yas/domain/routine/service/Status.java
Labels: 🐞BugFix, 🚀Deploy

#315 Fix : #312/루틴진행 상세조회시 루틴진행 후기 작성안했을때 조회 안되는 문제 해결
  src/main/java/org/prgrms/yas/domain/mission/service/MissionStatusService.java
Labels: 🐞BugFix

#317 Feat : #316/루틴완료 삭제 API 추가
  src/main/java/org/prgrms/yas/domain/routine/controller/RoutineStatusController.java
  src/main/java/org/prgrms/yas/domain/routine/domain/RoutineStatus.java
  src/main/java/org/prgrms/yas/domain/routine/service/RoutineStatusService.java
Labels: ✨Feature

#318 Feat : #316/루틴완료 삭제 API 추가
  src/main/java/org/prgrms/yas/domain/mission/service/MissionStatusService.java
  src/main/java/org/prgrms/yas/domain/routine/controller/RoutineStatusController.java
  src/main/java/org/prgrms/yas/domain/routine/domain/RoutineStatus.java
  src/main/java/org/prgrms/yas/domain/routine/service/RoutineStatusService.java
Labels: ✨Feature, 🚀Deploy, 🔧Refactor

#321 Fix : #320/루틴후기 등록 오류 해결
  src/main/java/org/prgrms/yas/domain/routine/domain/RoutineStatus.java
Labels: 🐞BugFix

#322 Fix : #develop/루틴후기등록 안되는 오류 해결
  src/main/java/org/prgrms/yas/domain/routine/domain/RoutineStatus.java
Labels: 🐞BugFix

#319 Test : #296/회원 Repository, Service 테스트 구현
  src/main/java/org/prgrms/yas/YasApplication.java
  src/main/java/org/prgrms/yas/configures/JpaAuditingConfig.java
  src/test/java/org/prgrms/yas/domain/user/repository/UserRepositoryTest.java
  src/test/java/org/prgrms/yas/domain/user/service/UserServiceTest.java
Labels: ✅Test

#323 deploy : 회원 테스트 추가 구현
  src/main/java/org/prgrms/yas/YasApplication.java
  src/main/java/org/prgrms/yas/configures/JpaAuditingConfig.java
  src/test/java/org/prgrms/yas/domain/user/repository/UserRepositoryTest.java
  src/test/java/org/prgrms/yas/domain/user/service/UserServiceTest.java
Labels: ✅Test, 🚀Deploy

#325 Hotfix : 테스트 코드 추후 수정을 위한 삭제
  src/main/java/org/prgrms/yas/domain/user/repository/UserRepository.java
  src/test/java/org/prgrms/yas/domain/user/service/UserServiceTest.java
Labels: 🐞BugFix, ✅Test

#326 deploy : 회원 테스트 코드 임시 수정후 배포
  src/main/java/org/prgrms/yas/domain/user/repository/UserRepository.java
  src/test/java/org/prgrms/yas/domain/user/service/UserServiceTest.java
Labels: 🐞BugFix, ✅Test

#328 Refactor : #327/routineStatus default값 변경
  src/main/java/org/prgrms/yas/domain/mission/service/MissionStatusService.java
  src/main/java/org/prgrms/yas/domain/routine/domain/RoutineStatus.java
Labels: 🔧Refactor

#329 Deploy : #develop/배포
  src/main/java/org/prgrms/yas/domain/mission/service/MissionStatusService.java
  src/main/java/org/prgrms/yas/domain/routine/domain/RoutineStatus.java
Labels: 🚀Deploy, 🔧Refactor

#331 Refactor : #330/루틴후기 상세조회시 미션상태 추가
  src/main/java/org/prgrms/yas/domain/routine/domain/Routine.java
  src/main/java/org/prgrms/yas/domain/routine/domain/RoutineStatus.java
  src/main/java/org/prgrms/yas/domain/routine/dto/RoutineDto.java
  src/main/java/org/prgrms/yas/domain/routine/dto/RoutineStatusDetailResponse.java
  src/main/java/org/prgrms/yas/domain/routine/service/RoutineStatusService.java
Labels: 🔧Refactor

#332 Deploy : #develop/배포
  src/main/java/org/prgrms/yas/domain/routine/domain/Routine.java
  src/main/java/org/prgrms/yas/domain/routine/domain/RoutineStatus.java
  src/main/java/org/prgrms/yas/domain/routine/dto/RoutineDto.java
  src/main/java/org/prgrms/yas/domain/routine/dto/RoutineStatusDetailResponse.java
  src/main/java/org/prgrms/yas/domain/routine/service/RoutineStatusService.java
Labels: 🚀Deploy, 🔧Refactor
