Repository prgrms-web-devcourse/Team_WAS_YAS_BE, pull requests merged in 2022-01, with the labels that each got.

#242 feat : #240/카카오 소셜로그인 기능 추가
  build.gradle
  src/main/java/org/prgrms/yas/configures/WebSecurityConfig.java
  src/main/java/org/prgrms/yas/domain/user/service/UserService.java
  src/main/java/org/prgrms/yas/oauth2/CookieUtil.java
  src/main/java/org/prgrms/yas/oauth2/HttpCookieOAuth2AuthorizationRequestRepository.java
  src/main/java/org/prgrms/yas/oauth2/OAuth2AuthenticationSuccessHandler.java
  src/main/resources/application-prod.yml
Labels: ✨Feature, ⚙️Setting

#244 deploy : 소셜로그인 배포
  README.md
  build.gradle
  src/main/java/org/prgrms/yas/configures/WebSecurityConfig.java
  src/main/java/org/prgrms/yas/domain/user/service/UserService.java
  src/main/java/org/prgrms/yas/oauth2/CookieUtil.java
  src/main/java/org/prgrms/yas/oauth2/HttpCookieOAuth2AuthorizationRequestRepository.java
  src/main/java/org/prgrms/yas/oauth2/OAuth2AuthenticationSuccessHandler.java
  src/main/resources/application-prod.yml
Labels: ✨Feature, 🚀Deploy

#245 Chore : 브랜치 동기화
  src/main/java/org/prgrms/yas/configures/WebSecurityConfig.java
Labels: ⚙️Setting, 📌Chore

#247 fix : #246/소셜 로그인 리다이렉트 주소 수정
  src/main/resources/application-prod.yml
Labels: 🐞BugFix

#248 deploy : 소셜 로그인 리다이렉트 주소 수정 후 배포
  src/main/resources/application-prod.yml
Labels: 🐞BugFix, 🚀Deploy

#254 feat : #253/회원가입시 이메일 중복 체크 기능 추가
  src/main/java/org/prgrms/yas/domain/user/controller/UserController.java
  src/main/java/org/prgrms/yas/domain/user/dto/UserEmailRequest.java
  src/main/java/org/prgrms/yas/domain/user/service/UserService.java
Labels: ✨Feature

#252 feat : #251/회원 비밀번호 변경 기능 추가
  src/main/java/org/prgrms/yas/domain/user/controller/UserController.java
  src/main/java/org/prgrms/yas/domain/user/domain/User.java
  src/main/java/org/prgrms/yas/domain/user/dto/UserPasswordRequest.java
  src/main/java/org/prgrms/yas/domain/user/service/UserService.java
Labels: ✨Feature

#255 deploy : 회원기능 추가
  src/main/java/org/prgrms/yas/domain/user/controller/UserController.java
  src/main/java/org/prgrms/yas/domain/user/domain/User.java
  src/main/java/org/prgrms/yas/domain/user/dto/UserEmailRequest.java
  src/main/java/org/prgrms/yas/domain/user/dto/UserPasswordRequest.java
  src/main/java/org/prgrms/yas/domain/user/service/UserService.java
Labels: ✨Feature, 🚀Deploy

#256 Fix : 회원컨트롤러 충돌 해결
  src/main/java/org/prgrms/yas/domain/user/controller/UserController.java
Labels: 🐞BugFix

#257 chore : 브랜치 동기화
  .github/workflows/deploy.yml
Labels: ⚙️Setting, 📌Chore

#259 refactor : #258/JWT 토큰 구조 변경
  src/main/java/org/prgrms/yas/domain/user/controller/UserController.java
  src/main/java/org/prgrms/yas/domain/user/dto/UserToken.java
  src/main/java/org/prgrms/yas/jwt/Jwt.java
  src/main/java/org/prgrms/yas/jwt/JwtAuthentication.java
  src/main/java/org/prgrms/yas/jwt/JwtAuthenticationFilter.java
  src/main/java/org/prgrms/yas/jwt/JwtAuthenticationProvider.java
  src/main/java/org/prgrms/yas/oauth2/OAuth2AuthenticationSuccessHandler.java
Labels: 🐞BugFix, 🔧Refactor

#260 deploy : JWT 토큰 구조 변경
  src/main/java/org/prgrms/yas/domain/user/controller/UserController.java
  src/main/java/org/prgrms/yas/domain/user/dto/UserToken.java
  src/main/java/org/prgrms/yas/jwt/Jwt.java
  src/main/java/org/prgrms/yas/jwt/JwtAuthentication.java
  src/main/java/org/prgrms/yas/jwt/JwtAuthenticationFilter.java
  src/main/java/org/prgrms/yas/jwt/JwtAuthenticationProvider.java
  src/main/java/org/prgrms/yas/oauth2/OAuth2AuthenticationSuccessHandler.java
Labels: 🐞BugFix, 🚀Deploy, 🔧Refactor

#262 refactor : #261/WebSecurityConfig 설정 추가
  src/main/java/org/prgrms/yas/configures/WebSecurityConfig.java
Labels: ⚙️Setting, 🔧Refactor

#264 Refactor : 소셜로그인 시 회원가입 데이터 수정
  src/main/java/org/prgrms/yas/domain/user/service/UserService.java
Labels: 🔧Refactor

#266 refactor : #265/이메일 중복 체크 컨트롤러 수정
  src/main/java/org/prgrms/yas/domain/user/controller/UserController.java
  src/main/java/org/prgrms/yas/domain/user/service/UserService.java
Labels: 🔧Refactor

#267 deploy : 회원 관련 수정 배포
  src/main/java/org/prgrms/yas/configures/WebSecurityConfig.java
  src/main/java/org/prgrms/yas/domain/user/controller/UserController.java
  src/main/java/org/prgrms/yas/domain/user/service/UserService.java
Labels: 🚀Deploy, 🔧Refactor

#270 refactor : #269/소셜로그인 시 프로필 사진 추가
  src/main/java/org/prgrms/yas/domain/user/service/UserService.java
  src/main/resources/application-prod.yml
Labels: 🔧Refactor

#272 refactor : #271/포스팅 가능한 루틴 조회 형식 변경
  src/main/java/org/prgrms/yas/domain/post/service/PostService.java
  src/main/java/org/prgrms/yas/domain/routine/repository/RoutineRepository.java
Labels: 🔧Refactor

#274 refactor : #273/비밀번호 에러 발생시 응답 변경
  src/main/java/org/prgrms/yas/domain/user/domain/User.java
  src/main/java/org/prgrms/yas/domain/user/dto/UserPasswordRequest.java
  src/main/java/org/prgrms/yas/domain/user/dto/UserSignUpRequest.java
  src/main/java/org/prgrms/yas/domain/user/exception/NotValidPasswordException.java
  src/main/java/org/prgrms/yas/global/error/ErrorCode.java
  src/main/java/org/prgrms/yas/global/error/GlobalExceptionHandler.java
Labels: 🔧Refactor

#249 feat : #241/루틴완료 후 후기 작성 기능 추가
  src/main/java/org/prgrms/yas/domain/routine/controller/RoutineStatusController.java
  src/main/java/org/prgrms/yas/domain/routine/domain/RoutineCategory.java
  src/main/java/org/prgrms/yas/domain/routine/domain/RoutineStatus.java
  src/main/java/org/prgrms/yas/domain/routine/domain/RoutineStatusImage.java
  src/main/java/org/prgrms/yas/domain/routine/dto/RoutineStatusCreateRequest.java
  src/main/java/org/prgrms/yas/domain/routine/exception/NotFoundRoutineStatusImageException.java
  src/main/java/org/prgrms/yas/domain/routine/repository/RoutineStatusImageRepository.java
  src/main/java/org/prgrms/yas/domain/routine/repository/RoutineStatusRepository.java
  src/main/java/org/prgrms/yas/domain/routine/service/RoutineStatusService.java
  src/main/java/org/prgrms/yas/global/aws/S3Uploader.java
Labels: ✨Feature

#275 deploy : 추가 수정사항 배포
  src/main/java/org/prgrms/yas/domain/post/service/PostService.java
  src/main/java/org/prgrms/yas/domain/routine/controller/RoutineStatusController.java
  src/main/java/org/prgrms/yas/domain/routine/domain/RoutineCategory.java
  src/main/java/org/prgrms/yas/domain/routine/domain/RoutineStatus.java
  src/main/java/org/prgrms/yas/domain/routine/domain/RoutineStatusImage.java
  src/main/java/org/prgrms/yas/domain/routine/dto/RoutineStatusCreateRequest.java
  src/main/java/org/prgrms/yas/domain/routine/exception/NotFoundRoutineStatusImageException.java
  src/main/java/org/prgrms/yas/domain/routine/repository/RoutineRepository.java
  src/main/java/org/prgrms/yas/domain/routine/repository/RoutineStatusImageRepository.java
  src/main/java/org/prgrms/yas/domain/routine/repository/RoutineStatusRepository.java
  src/main/java/org/prgrms/yas/domain/routine/service/RoutineStatusService.java
  src/main/java/org/prgrms/yas/domain/user/domain/User.java
  src/main/java/org/prgrms/yas/domain/user/dto/UserPasswordRequest.java
  src/main/java/org/prgrms/yas/domain/user/dto/UserSignUpRequest.java
  src/main/java/org/prgrms/yas/domain/user/exception/NotValidPasswordException.java
  src/main/java/org/prgrms/yas/domain/user/service/UserService.java
  src/main/java/org/prgrms/yas/global/aws/S3Uploader.java
  src/main/java/org/prgrms/yas/global/error/ErrorCode.java
  src/main/java/org/prgrms/yas/global/error/GlobalExceptionHandler.java
  src/main/resources/application-prod.yml
Labels: 🚀Deploy

#276 feat : #250/루틴완료시 날짜별 전체/상세 조회, 루틴완료 상세 조회 기능 추가
  src/main/java/org/prgrms/yas/domain/routine/controller/RoutineStatusController.java
  src/main/java/org/prgrms/yas/domain/routine/domain/RoutineStatus.java
  src/main/java/org/prgrms/yas/domain/routine/dto/RoutineStatusDetailResponse.java
  src/main/java/org/prgrms/yas/domain/routine/dto/RoutineStatusImageDto.java
  src/main/java/org/prgrms/yas/domain/routine/dto/RoutineStatusListResponse.java
  src/main/java/org/prgrms/yas/domain/routine/repository/RoutineStatusRepository.java
  src/main/java/org/prgrms/yas/domain/routine/service/RoutineStatusService.java
Labels: ✨Feature

#278 feat : #277/파일이름에 uuid 추가하여 같은 이름 파일 올라와도 구분할 수 있게 처리
  src/main/java/org/prgrms/yas/domain/routine/service/RoutineStatusService.java
  src/main/java/org/prgrms/yas/global/aws/S3Uploader.java
Labels: 🔧Refactor

#280 refactor : #279루틴후기 작성시 컬럼명 변경 emoji -> emotion
  src/main/java/org/prgrms/yas/domain/routine/domain/RoutineStatus.java
  src/main/java/org/prgrms/yas/domain/routine/dto/RoutineStatusCreateRequest.java
  src/main/java/org/prgrms/yas/domain/routine/dto/RoutineStatusDetailResponse.java
Labels: 🔧Refactor

#281 feat : #develop/머지
  src/main/java/org/prgrms/yas/domain/routine/controller/RoutineStatusController.java
  src/main/java/org/prgrms/yas/domain/routine/domain/RoutineStatus.java
  src/main/java/org/prgrms/yas/domain/routine/dto/RoutineStatusCreateRequest.java
  src/main/java/org/prgrms/yas/domain/routine/dto/RoutineStatusDetailResponse.java
  src/main/java/org/prgrms/yas/domain/routine/dto/RoutineStatusImageDto.java
  src/main/java/org/prgrms/yas/domain/routine/dto/RoutineStatusListResponse.java
  src/main/java/org/prgrms/yas/domain/routine/repository/RoutineStatusRepository.java
  src/main/java/org/prgrms/yas/domain/routine/service/RoutineStatusService.java
  src/main/java/org/prgrms/yas/global/aws/S3Uploader.java
Labels: ✨Feature, 🚀Deploy, 🔧Refactor

#287 feat : #286/슬랙과 로그 기록 연동
  build.gradle
  src/main/resources/application.yml
  src/main/resources/logback-spring.xml
Labels: ✨Feature

#283 fix : #282/댓글 좋아요 관련 오류 해결
  src/main/java/org/prgrms/yas/domain/comment/domain/Comment.java
  src/main/java/org/prgrms/yas/domain/likes/domain/CommentLikes.java
Labels: 🐞BugFix

#288 deploy : 슬랙 연동 및 댓글 에러 해결 배포
  build.gradle
  src/main/java/org/prgrms/yas/domain/comment/domain/Comment.java
  src/main/java/org/prgrms/yas/domain/likes/domain/CommentLikes.java
  src/main/resources/application.yml
  src/main/resources/logback-spring.xml
Labels: 🐞BugFix, ✨Feature
